
function mux_config(this_block)

  % Revision History:
  %
  %   13-Dec-2022  (20:59 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\HP\OneDrive\Desktop\vlsi\black_box\32bitrom\mux4x1.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('mux');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('a');
  this_block.addSimulinkInport('b');
  this_block.addSimulinkInport('c');
  this_block.addSimulinkInport('d');
  this_block.addSimulinkInport('s0');
  this_block.addSimulinkInport('s1');

  this_block.addSimulinkOutport('dout');

  dout_port = this_block.port('dout');
  dout_port.setType('UFix_8_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('a').width ~= 8);
      this_block.setError('Input data type for port "a" must have width=8.');
    end

    if (this_block.port('b').width ~= 8);
      this_block.setError('Input data type for port "b" must have width=8.');
    end

    if (this_block.port('c').width ~= 8);
      this_block.setError('Input data type for port "c" must have width=8.');
    end

    if (this_block.port('d').width ~= 8);
      this_block.setError('Input data type for port "d" must have width=8.');
    end

    if (this_block.port('s0').width ~= 1);
      this_block.setError('Input data type for port "s0" must have width=1.');
    end

    this_block.port('s0').useHDLVector(false);

    if (this_block.port('s1').width ~= 1);
      this_block.setError('Input data type for port "s1" must have width=1.');
    end

    this_block.port('s1').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('mux4x1.v');

return;


